/** Starter templates clients can merge into their planning checklist (customizable after apply). */
export const EVENT_CHECKLIST_TEMPLATES = [
  {
    id: "general",
    name: "General event",
    description: "Venue, timeline, and wrap-up basics",
    items: [
      "Confirm date & final guest count",
      "Send invites / save-the-dates",
      "Book main venue or location",
      "Plan seating or floor layout",
      "Arrange parking / directions for guests",
      "Coordinate day-of timeline with vendors",
      "Prepare backup plan for weather (if outdoor)",
      "Collect RSVPs and dietary notes",
      "Finalize payments & gratuities",
      "Pack emergency kit (tape, scissors, chargers)",
    ],
  },
  {
    id: "wedding",
    name: "Wedding",
    description: "Ceremony & reception checklist",
    items: [
      "Legal paperwork / officiant confirmed",
      "Ceremony & reception venues booked",
      "Photography & videography slots",
      "Catering tasting & final menu",
      "Cake / dessert ordered",
      "Florals & décor theme locked",
      "Music playlist & first dance",
      "Hair & makeup trials",
      "Transportation for wedding party",
      "Rehearsal scheduled",
      "Thank-you speech notes",
    ],
  },
  {
    id: "corporate",
    name: "Corporate / seminar",
    description: "Programs, AV, and branding",
    items: [
      "Venue contract & room layout",
      "Registration / ticketing",
      "AV, mic checks, and backup laptop",
      "Branding: banners, slides, name badges",
      "Catering & coffee breaks",
      "Speaker travel & accommodation",
      "Wi‑Fi & guest access",
      "Photography / recap video",
      "Post-event survey",
    ],
  },
  {
    id: "birthday",
    name: "Birthday party",
    description: "Smaller gatherings",
    items: [
      "Pick theme & decorations",
      "Send invitations",
      "Order cake",
      "Party playlist",
      "Games / entertainment",
      "Photo corner or booth",
      "Party favors",
      "Cleanup plan",
    ],
  },
];
